[project]
name = "evening-class-notes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Karthikeya", email = "kamalkarthikeyakumar@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
evening-class-notes = "evening_class_notes:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
